# Generated by Django 4.2.3 on 2023-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='thing',
            field=models.CharField(blank=True, choices=[('dumbbell', '初級小物/dumbbell'), ('energy_drink', '中級小物/energy_drink'), ('protein_powder', '高級小物/protein_powder')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('bicep_curl', 'bicep_curl'), ('push_up', 'push_up'), ('squat', 'squat')], default='bicep_curl', max_length=15),
        ),
    ]
