# Generated by Django 4.2.3 on 2023-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_thing_alter_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
