# Generated by Django 4.2.3 on 2023-09-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exercise_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gear'),
        ),
    ]
