# Generated by Django 4.2.3 on 2023-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='trial',
            field=models.BooleanField(default=False),
        ),
    ]
