# Generated by Django 4.2.3 on 2023-10-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gear_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'basic'), (1, 'intermediate'), (2, 'advanced'), (3, 'trial')]),
        ),
        migrations.AlterField(
            model_name='gear',
            name='token_id',
            field=models.IntegerField(),
        ),
    ]
