# Generated by Django 4.2.3 on 2023-10-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gear_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='max',
            field=models.BooleanField(default=False),
        ),
    ]
